name: 'Git-Test Setup'
author: '@awseward'
description: Set up https://github.com/mhagger/git-test for use in a GitHub Action

inputs:
  git_test_dir:
    description: |
      Where to clone `git-test` (relative to $GITHUB_WORKSPACE).
      The `git-test` binary will then be located at `$git_test_dir/bin/git-test`
    required: false
    default: .git-test

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: mhagger/git-test
        # TODO: Probably parameterize this if we can
        path: ${{ inputs.git_test_dir }}

    - run: echo "PATH=${PATH}:${GITHUB_WORKSPACE}/${{ inputs.git_test_dir }}/bin" >> "${GITHUB_ENV}" && echo "${PATH}"
      shell: bash

    # TODO: Parameterize this
    - run: git config --local user.email "git-test.user@example.com"
      shell: bash

    # TODO: Parameterize this
    - run: git config --local user.name "Git-Test User"
      shell: bash

    # TODO: Parameterize this
    - run: git test add './test.sh'
      shell: bash
